---
- include_role:
    name: openio-service
  vars:
    openio_service_type: "prometheus"
    openio_service_namespace: "{{ openio_prometheus_namespace }}"
    openio_service_maintenance_mode: "{{ openio_prometheus_maintenance_mode }}"
    openio_service_packages:
      - oio-prometheus
    openio_service_directories:
      - path: "{{ openio_service_conf_dir }}/rules"
      - path: "{{ openio_service_volume }}"
    openio_service_configuration_files:
      - name: rules/openio.alerts.yml
        block_start_string: '§%'
        block_end_string: '%§'
        variable_start_string: '§!!'
        variable_end_string: '!!§'
      - name: rules/openio.aggregation.yml
        block_start_string: '§%'
        block_end_string: '%§'
        variable_start_string: '§!!'
        variable_end_string: '!!§'
      #
      # Ensure to put prometheus.yml at the end of the list
      # so that the validate command will be able to access
      # included rules files
      #
      - name: prometheus.yml
        validate: "/usr/bin/oio-promtool check config %s"
    openio_service_services:
      - command: >-
          /usr/sbin/oio-prometheus
          --web.console.libraries=/usr/share/oio-prometheus/console_libraries
          --web.console.templates=/usr/share/oio-prometheus/consoles
          --storage.tsdb.path={{ openio_service_volume }}
          --web.listen-address={{ openio_prometheus_bind_address }}:{{ openio_prometheus_bind_port }}
          --web.external-url=http://{{ openio_prometheus_ext_bind_address }}:{{ openio_prometheus_ext_bind_port }}
          --web.enable-lifecycle
          --storage.tsdb.retention={{ openio_prometheus_storage_rentention }}
          --config.file={{ openio_service_conf_dir }}/prometheus.yml
          --log.level={{ openio_prometheus_log_level }}
        redirect_stdout_to_syslog: true
        limits: "{{ openio_prometheus_limits }}"
    openio_service_checks:
      - uri:
          url: "http://{{ openio_prometheus_bind_address }}:{{ openio_prometheus_bind_port }}/-/ready"
        retries: 10
        delay: 2
...
