---

- name: "Prometheus: checks"
  include: preflight.yml

- block:
    - name: "Prometheus: install"
      include: "install/{{ ansible_distribution }}.yml"

    - name: "Prometheus: configure"
      include: "configure.yml"
      notify: reload prometheus

    - name: "Prometheus: setup netdata"
      template:
        src: netdata.yml.j2
        dest: "{{ prometheus_conf_dir }}/targets/netdata.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      notify: reload prometheus
  when: inventory_hostname == prometheus_admin_host

- name: "Prometheus: setup healthchecks"
  include: "healthchecks.yml"
  notify: reload prometheus

- block:
    - name: "Prometheus: start service"
      systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: "prometheus"

    - name: "Prometheus: wait for service to start"
      wait_for:
        host: "{{ prometheus_listen_ip }}"
        port: "{{ prometheus_listen_port }}"
        delay: 10
  when: inventory_hostname == prometheus_admin_host
...
